# GENERAL
backend = "glx";
vsync = true;
detect-rounded-corners = false;
detect-client-opacity = false;
detect-transient = true;
unredir-if-possible = true;



# CORNERS
#corner-radius = 11;

# Exclude conditions for rounded corners.
#rounded-corners-exclude = [
#  "window_type = 'dock'",
#  "window_type = 'desktop'"
#];

blur: {
  method = "dual_kawase";
  strength = 6;
  background = true;
  background-frame = false;
  background-fixed = false;
}


# Exclude conditions for background blur.
# blur-background-exclude = []
blur-background-exclude = [
  "role = 'xborder'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Chromium'",
  "class_g = 'Discord'",
  "class_g = 'Dunst'",
  "class_g = 'Peek'",
  "class_g *?= 'slop'",
];
