[mgr]
prepend_keymap = [
  # dual-pane
	{ on = "\\",       run = "plugin split-tabs spl_toggle", desc = "Dual-pane: toggle" },
	{ on = "<Tab>",    run = "plugin split-tabs spl_switch_tab", desc = "Dual-pane: switch pane" },
	{ on = "P",        run = "plugin split-tabs spl_preview", desc = "Dual-pane: toggle bottom preview" },
  # preview pane
	{ on = "<C-g>",    run = "shell -- rofi -theme fullscreen-preview -show filebrowser -filebrowser-command \"ya emit reveal\" -filebrowser-directory \"$(pwd)\"", desc = "Grid view" },
  # parent-arrow
	{ on = "<C-k>",    run = "plugin parent-arrow -1" },
	{ on = "<C-j>",    run = "plugin parent-arrow 1" },

	# restore
	{ on = "u",          run = "plugin restore", desc = "Restore last deleted files/folders" },
	{ on = ["i", "u"], run = "plugin restore -- --interactive", desc = "Restore deleted files/folders (Interactive)" },
	{ on = ["i", "U"], run = "plugin restore -- --interactive --interactive-overwrite", desc = "Restore deleted files/folders (Interactive overwrite)" },

  # zoxide
  { on = [ "z" ], run = "plugin zoxide", desc = "Jump via zoxide" },
  { on = [ "Z" ], run = "shell -- zoxide add \"$PWD\"", desc = "Add cwd to zoxide" },
  { on = [ "i", "z" ], run = "shell --block -- zoxide edit", desc = "Edit zoxide database" },
]
