# Fonts
font_size 18
font_family      Fira Code Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

# Tabs
tab_bar_edge bottom
tab_bar_min_tabs 2
tab_bar_style powerline
tab_powerline_style slanted
tab_title_max_length 20

# Cursor
cursor_stop_blinking_after 0
cursor_trail 1
cursor_trail_decay 0.1 0.2

# Scrollback
scrollback_lines 10000

# Mouse
url_color #ff00ff
url_style double
detect_urls yes
show_hyperlink_targets yes
underline_hyperlinks always

# Color scheme
foreground #dddddd
background #000000
background_opacity 0.8
background_blur 1
dynamic_background_opacity yes

# Advanced
shell zsh -l
editor .
close_on_child_death no
allow_hyperlinks yes

# Keymaps
map ctrl+a>q close_window
map ctrl+a>minus launch --location=hsplit
map ctrl+a>pipe launch --location=vsplit

map ctrl+a>shift+h move_window left
map ctrl+a>shift+j move_window down
map ctrl+a>shift+k move_window up
map ctrl+a>shift+l move_window right

map ctrl+a>h neighboring_window left
map ctrl+a>j neighboring_window down
map ctrl+a>k neighboring_window up
map ctrl+a>l neighboring_window right

map ctrl+a>left  resize_window narrower
map ctrl+a>right resize_window wider
map ctrl+a>up		 resize_window taller
map ctrl+a>down  resize_window shorter 3
map ctrl+a>home  resize_window reset
